/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/views/home/home.vue')['default']
    LjqInput: typeof import('./src/views/login/common/ljq-input.vue')['default']
    LogForm: typeof import('./src/views/login/components/log-form.vue')['default']
    Login: typeof import('./src/views/login/login.vue')['default']
    LogIn: typeof import('./src/views/login/components/log-in.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/views/login/components/sign-up.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
