image: node:18

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  script:
    - npm install -g vercel
    - vercel login --token=$VERCEL_TOKEN
    - vercel --prod --scope=$VERCEL_ORG_ID --project-id=$VERCEL_PROJECT_ID --prebuilt --cwd=dist